name: RandomTP
main: me.doobles.RandomTP
version: 1.0
commands:
   shorttp:
      description: Teleports player a short distance out
      usage: /<command>
   mediumtp:
      description: Teleports player a medium distance out
      usage: /<command>
   fartp:
      description: Teleports player a far distance out
      usage: /<command>
   wild:
      description: Teleports player to a random location in the wild
      usage: /<command>
